apps/login_reg_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^all$', views.all, name='all'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout')
]

travel_buddy/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^main/', include('apps.login_reg_app.urls', namespace='users')),
    url(r'^travels/', include('apps.travels_app.urls', namespace='travels')),
]

apps/login_reg_app/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt
from django.utils.encoding import python_2_unicode_compatible
#import re
#email_regex = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
#found a name regex from online
#name_regex = re.compile(r'^[A-Z][-a-zA-Z]+$')


class UserManager(models.Manager):
    def login(self, form_data):
        print("Validating login")
        # retrieve the user from database using email
        user = User.objects.filter(username=form_data['username'])
        if user:
            print('Username found in database')
            user = user[0]
            if bcrypt.checkpw(form_data['pw'].encode(), user.pw_hash.encode()):
                print("passwords match")
                # returning user object to views
                return (True, user)
        return (False, "Invalid username or password")

    def register(self, form_data):
        # Validation portion. Pushes all errors to an array that is returned if there are errors
        errors = []
        # if not name_regex.match(form_data['name']):
        #     errors.append("Invalid name")
        # if not name_regex.match(form_data['username']):
        #     errors.append("Invalid username")
        if len(form_data['name']) < 3 or len(form_data['username']) < 3:
            errors.append("Name or username must be 3 or more characters in length")
        if len(form_data['pw']) < 8:
            errors.append("Password must be 8 or more characters in length")
        if form_data['pw'] != form_data['pw_confirmation']:
            errors.append("Password must match password confirmation")
        user = User.objects.filter(username=form_data['username'])
        if user:
            errors.append("Username has already been used")
        # checks if there were any errors
        if len(errors) is not 0:
            return (False, errors)
        else:
            print("passed validations")
            # create the hashed password using bcrypt. Remember to encode
            pw_hash = bcrypt.hashpw(form_data['pw'].encode(), bcrypt.gensalt().encode())
            # create() method in objects returns newly entered entry in your db
            user = User.objects.create(username=form_data['username'], name=form_data['name'], pw_hash=pw_hash)
            return (True, user)

class User(models.Model):
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    pw_hash = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()
    def __str__(self):              # __unicode__ on Python 2
        return self.name

apps/login_reg_app/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
    if 'user_id' in request.session:
        return redirect(reverse('travels:index'))
    else:
        return render(request, 'login_reg_app/index.html')

# shows a list of all users for debugging purposes ;)
def all(request):
    users = User.objects.all()
    context = {
        'users': users
    }
    return render(request, 'login_reg_app/all.html', context)

def register(request):
    if request.method == 'POST':
        validation = User.objects.register(request.POST)
        if validation[0]:
            return log_user_in(request, validation[1])
        else:
            for error in validation[1]:
                messages.error(request, error)
            return redirect(reverse('users:index'))
    return redirect(reverse('users:index'))
def login(request):
    if request.method == 'POST':
        validation = User.objects.login(request.POST)
        if validation[0]:
            return log_user_in(request, validation[1])
        else:
            messages.error(request, validation[1])
    return redirect(reverse('users:index'))

def log_user_in(request, user):
    print("running log_user_in function")
    request.session['user_id'] = user.id
    # add user to success flash message
    messages.success(request, "Welcome, {}. You are logged in.".format(user.name))
    return redirect(reverse('travels:index'))

def logout(request):
    if 'user_id' in request.session:
        del request.session['user_id']
        messages.success(request, "You have been successfully logged out")
        return redirect(reverse('users:index'))
    else:
        messages.error(request, "You were not logged in")
        return redirect(reverse('users:index'))

apps/login_reg_app/templates/login_reg_app/all.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>List of all users</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'login_reg_app/css/styles.css' %}"media="screen" title="no title"  charset="utf-8">
    </head>
    <body>
        <h1>Users:</h1>
        {% if messages %}
            <ul class='messages'>
            {% for message in messages %}
                <li {% if message.tags %}class='{{message.tags}}'{% endif %}>{{message}}</li>
            {% endfor %}
            </ul>
        {% endif %}
        {% if users %}
            <table>
                <tr class='row1'>
                    <th>Name</th>
                    <th>Username</th>
                    <th>User ID</th>
                </tr>
                {% for user in users %}
                <tr class="{% cycle 'row2' 'row1' %}">
                    <th>{{user.name}}</th>
                    <th>{{user.username}}</th>
                    <th>{{user.id}}</th>
                </tr>
                {% endfor %}
            </table>
        {% endif %}
        <a href="{% url 'users:logout' %}">Logout</a>
    </body>
</html>

apps/login_reg_app/templates/login_reg_app/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Login</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'login_reg_app/css/styles.css' %}"media="screen" title="no title"  charset="utf-8">
    </head>
    <body>
        <h1>Login and Registration</h1>
        {% if messages %}
            <ul class='messages'>
            {% for message in messages %}
                <li {% if message.tags %}class='{{message.tags}}'{% endif %}>{{message}}</li>
            {% endfor %}
            </ul>
        {% endif %}
        <div id="register">
            <h2>Register</h2>
            <form class="" action="{% url 'users:register' %}" method="post">
                {% csrf_token %}
                Name: <input type="text" name="name" value="">
                <br>
                Username: <input type="text" name="username" value="">
                <br>
                Password: <input type="password" name="pw" value="">
                <br>
                <p>Password should be at least 8 characters*</p>
                Confirm Password: <input type="password" name="pw_confirmation" value="">
                <br>
                <input type="submit" name="submit" value="Register">
            </form>
        </div>
        <br>
        <div id="login">
            <h2>Login</h2>
            <form class="" action="
            {% url 'users:login' %}" method="post">
                {% csrf_token %}
                Username: <input type="text" name="username" value="">
                <br>
                Password: <input type="password" name="pw" value="">
                <br>
                <input type="submit" name="login" value="Login">
            </form>
        </div>
    </body>
</html>